# loc() method
## Label-based
## Inclusive
# SYNTAX = df.loc[row_label, column_label]

In [1]:
import pandas as pd

In [84]:
df = pd.read_csv("players_20.csv")
df.set_index("short_name" , inplace = True)
df = df[[ "long_name" , "age" ,"dob" , "height_cm" , "weight_kg" , "nationality" , "club"]]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [26]:
# get all data of lionel messi
df.loc["L. Messi" ]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [19]:
# get weight of Cristiano Ronaldo
df.loc["Cristiano Ronaldo" , "weight_kg"]

np.int64(83)

In [ ]:
# get all rows inside "height_cm" column
df.loc[ :, "height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [ ]:
# get all data about l messi anf ronaldo
df.loc[["L. Messi" , "Cristiano Ronaldo"]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [29]:
# get height of l messi anf ronaldo
df.loc[["L. Messi" , "Cristiano Ronaldo"] , "height_cm"]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [31]:
# get height and weight of l messi
df.loc["L. Messi" , "height_cm" : "weight_kg"]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [32]:
# get height and weight of l messi and ronaldo
df.loc["L. Messi":"Cristiano Ronaldo" , "height_cm" : "weight_kg"]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## Selecting Range of data with a slice
### start : stop : step
### start and stop included

In [35]:
players = ["L. Messi" , "Cristiano Ronaldo"]
df.loc[players , "age" : "club"]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [43]:
# select top 10 players with thier age to weight
df.loc['L. Messi': 'M. Salah', 'age':'weight_kg']

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

## Selecting based on condition

In [46]:
df.loc[df["height_cm"]  > 180  , 'age' : 'club' ].head()

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool

In [51]:
# height above 180 from argentina
con1 = df['height_cm'] > 180
con2 = df["nationality"] == "Argentina"
df.loc[con1 & con2 , :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

# iloc Syntax
## df.iloc[row_position, column_position]
### Uses integer positions only — starts from 0, end is exclusive.

In [52]:
# get height of messi
df.iloc[0,3]

np.int64(170)

In [53]:
# weight of cr
df.iloc[1,4]

np.int64(83)

In [58]:
# get all rows inside the "height_cm"
df.iloc[: , 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [61]:
# get all columns that correspond to the index "L. Messi"
df.iloc[0,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [67]:
# get all data about L.Messi and ronaldo
df.iloc[0:2, :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [68]:
# get height of messi and ronaldo
df.iloc[0:2 , 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [70]:
# get height and weight of messi
df.iloc[0,3:5]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [71]:
# get height and weight of l . messi and ronaldo
df.iloc[0:2 , 3:5]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [72]:
# get age, dob, height and weight of top 10 players
df.iloc[0:10 , 1:5]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

In [78]:
# select players with height above 180 cm from age to weight
cond = df['height_cm']  >180 
df.iloc[list(cond) , 1:5]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [83]:
# select players with height above 180 cm and nationality is argentina from age to nationality
cond1 = df['height_cm'] > 180
cond2 = df['nationality'] == 'Argentina'
df.iloc[list(cond1 & cond2) , 1:6]

                age         dob  height_cm  weight_kg nationality
short_name
M. Icardi        26  1993-02-19        181         75   Argentina
G. Higuaín       31  1987-12-10        186         89   Argentina
E. Garay         32  1986-10-10        189         90   Argentina
N. Otamendi      31  1988-02-12        183         81   Argentina
G. Rulli         27  1992-05-20        189         84   Argentina
...             ...         ...        ...        ...         ...
T. Durso         20  1999-02-26        185         80   Argentina
J. Hass          21  1998-03-27        186         88   Argentina
R. Ferrario      19  2000-04-30        186         76   Argentina
L. Finochietto   22  1997-04-25        186         77   Argentina
N. Forastiero    20  1998-07-16        182         79   Argentina

[350 rows x 5 columns]