# WEB SCRAPPING- Web scraping is the process of automatically extracting data from websites using code.

In [ ]:
import pandas as pd

In [ ]:
# CREATING A DATAFRAME FROM A CSV FILE df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv
')

In [4]:
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,E0,25/04/2026,15:00,Liverpool,Crystal Palace,3,1,H,2,0,...,1.98,1.88,NaN,NaN,1.98,1.90,1.92,1.85,NaN,NaN
335,E0,25/04/2026,15:00,West Ham,Everton,2,1,H,0,0,...,1.78,2.10,NaN,NaN,1.78,2.10,1.75,2.04,NaN,NaN
336,E0,25/04/2026,15:00,Wolves,Tottenham,0,1,A,0,0,...,2.05,1.80,NaN,NaN,2.05,1.86,1.99,1.79,NaN,NaN
337,E0,25/04/2026,17:30,Arsenal,Newcastle,1,0,H,1,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.84,1.94,NaN,NaN
338,E0,27/04/2026,20:00,Man United,Brentford,2,1,H,2,0,...,2.03,1.83,NaN,NaN,2.03,1.85,1.90,1.81,NaN,NaN

In [7]:
# RENAMING COLUMNS
df_premier25.rename(columns = {'FTHG':'home_goals' , 'FTAG':'away_goals' },inplace = True)
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,E0,25/04/2026,15:00,Liverpool,Crystal Palace,3,1,H,2,0,...,1.98,1.88,NaN,NaN,1.98,1.90,1.92,1.85,NaN,NaN
335,E0,25/04/2026,15:00,West Ham,Everton,2,1,H,0,0,...,1.78,2.10,NaN,NaN,1.78,2.10,1.75,2.04,NaN,NaN
336,E0,25/04/2026,15:00,Wolves,Tottenham,0,1,A,0,0,...,2.05,1.80,NaN,NaN,2.05,1.86,1.99,1.79,NaN,NaN
337,E0,25/04/2026,17:30,Arsenal,Newcastle,1,0,H,1,0,...,1.88,1.98,NaN,NaN,1.88,1.98,1.84,1.94,NaN,NaN
338,E0,27/04/2026,20:00,Man United,Brentford,2,1,H,2,0,...,2.03,1.83,NaN,NaN,2.03,1.85,1.90,1.81,NaN,NaN

## Reading .csv from multiple URL's with pandas

In [8]:
# link structure:
"https://football-data.co.uk/mmz4281/" +"2526" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [9]:
# create a root variable
root = "https://football-data.co.uk/mmz4281/"

## MULTIPLE LINKS
- https://football-data.co.uk/mmz4281/2526/E0.csv
- https://football-data.co.uk/mmz4281/2526/E1.csv
- https://football-data.co.uk/mmz4281/2526/E2.csv
- https://football-data.co.uk/mmz4281/2526/E3.csv
- https://football-data.co.uk/mmz4281/2526/EC.csv

In [ ]:
# creating a list of leagues
leagues = ['E0' , 'E1', 'E2' ,'E3' ,'EC']
frames = [] # empty list to store dataframes
for league in leagues:
    df= pd.read_csv( root + "2526" + "/" + league + ".csv" )
    frames.append(df)

In [12]:
len(frames)
frames[2].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04
3,E2,02/08/2025,15:00,Bradford,Wycombe,2,1,H,2,0,...,1.73,2.08,1.90,1.99,1.77,2.20,1.72,2.02,1.80,2.22
4,E2,02/08/2025,15:00,Burton,Mansfield,2,1,H,1,0,...,2.00,1.85,1.69,2.26,2.00,1.85,1.93,1.79,2.04,1.93